// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfkeo5sb6VgyoIMl7Awr0dXSm1zbvfeZY',
    appId: '1:486106589023:web:c0ef2ab931f1600665b8ea',
    messagingSenderId: '486106589023',
    projectId: 'movieapp-e5c87',
    authDomain: 'movieapp-e5c87.firebaseapp.com',
    storageBucket: 'movieapp-e5c87.appspot.com',
    measurementId: 'G-4PLSV29PZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_VN93GUFHbuaU_DAOkcMAP_g-mSrXw9o',
    appId: '1:486106589023:android:1d476890fc1993c465b8ea',
    messagingSenderId: '486106589023',
    projectId: 'movieapp-e5c87',
    storageBucket: 'movieapp-e5c87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKY2UsepUtAke0CJzm_QaB-i-tP5FTnQs',
    appId: '1:486106589023:ios:95eb9c373be2acea65b8ea',
    messagingSenderId: '486106589023',
    projectId: 'movieapp-e5c87',
    storageBucket: 'movieapp-e5c87.appspot.com',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKY2UsepUtAke0CJzm_QaB-i-tP5FTnQs',
    appId: '1:486106589023:ios:ca0bb50103f1fee365b8ea',
    messagingSenderId: '486106589023',
    projectId: 'movieapp-e5c87',
    storageBucket: 'movieapp-e5c87.appspot.com',
    iosBundleId: 'com.example.movieapp.RunnerTests',
  );
}
